<?php require 'templates/header.phtml';?>
<h2>Editar Marca</h2>
<form action="editarMarca/<?= $marca[0]->id_marca ?>" method="POST">
    <label for="nombre">Nombre:</label>
    <input type="text" id="nombre" name="nombre" value="<?= $marca[0]->nombre ?>" required>
    
    <label for="sede">Sede:</label>
    <input type="text" id="sede" name="sede" value="<?= $marca[0]->sede ?>" required>
    <label for="foto">Imagen</label>
    <input type="text" id="foto" name="foto" value="<?= $marca[0]->foto?>" placeholder="Ingrese URL de a imagen">
    
    <button type="submit">Guardar Cambios</button>
</form>

<?php 
require 'templates/header.phtml';