<?php 
require 'temlpates/hearder.phtml';
?>
<h2>Editar Marca</h2>
<form action="<?= BASE_URL ?>editar/<?= $marca->id_marca ?>" method="POST">
    <label for="nombre">Nombre:</label>
    <input type="text" id="nombre" name="nombre" value="<?= $marca->nombre ?>" required>
    
    <label for="sede">Sede:</label>
    <input type="text" id="sede" name="sede" value="<?= $marca->sede ?>" required>
    
    <button type="submit">Guardar Cambios</button>
</form>

<?php 
require 'templates/header.phtml';