<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>Marcas</title>
</head>

<body>

    <header>
        <h1><a href="marcas">CATALOGO - BOTINES</a></h1> 
        <?php if($this->usuario): ?>
            <div>
                <a href="logout">Cerrar sesión</a>
            </div>
            <?php endif; ?>
        <nav>
            <div>
                <a href="botines">Botines</a>
                <a href="marcas">Marcas</a>
            </div>
                
        </nav>
    </header>
   
