<form action="insertar" method="POST">
    
    <label>Modelo</label>
        <input required name="modelo" type="text"> <!-- ver los required -->
    <label>Color</label>
        <input required name="color" type="text"> <!-- ver los required -->
    <label>Talle</label>
        <input required name="talle" type="number"> <!-- ver los required -->
    <label>Gama</label>
        <input required name="gama" type="text"> <!-- ver los required -->
    <label>Precio</label>
        <input required name="precio" type="number"> <!-- ver los required -->
    <label>Marca</label>
        <select required name="id_marca">
            <?php foreach($marcas as $marca) { ?>
            <option value="<?= $marca->id_marca ?>"> <?= $marca->nombre ?></option>
            <?php } ?>
        </select>

    <button type="submit">Guardar</button>

</form>