<form action="insertar" method="POST">
    
    <label>Modelo</label>
        <input required name="modelo" type="text"> 
    <label>Color</label>
        <input required name="color" type="text"> 
    <label>Talle</label>
        <input required name="talle" type="number"> 
    <label>Gama</label>
        <input required name="gama" type="text"> 
    <label>Precio</label>
        <input required name="precio" type="number"> 
    <label>Marca</label>
        <select required name="id_marca">
            <?php foreach($botinesConMarcas as $botin) { ?>
            <option value="<?= $botin->id_marca ?>"> <?= $botin->nombre_marca ?></option>
            <?php } ?>
        </select>

    <button type="submit">Guardar</button>

</form>