<form action="insertarMarca" method="POST">
    
    <label>Marca</label>
        <input required name="nombre" type="text" placeholder="Nombre de la Marca"> 
    <label>Sede</label>
        <input required name="sede" type="text" placeholder="Sede de la Marca"> 
    <label>Foto</label>
        <input name="foto" type="text" placeholder="Ingresar URL de la imagen.">
   

    <button type="submit">Guardar</button>

</form>