<?php 
 require_once "templates/header.phtml";
 require_once "templates/insertar_marcas.phtml";
?>      

<ul>
    <?php foreach($marcas as $marca) {?>
        <img src="<?= $marca->foto ?>">
        <li>
            <?= $marca->nombre ?> | Sede: <?= $marca->sede?>
            <a href="eliminarMarca/<?= $marca->id_marca?>" type="button">Borrar</a>
            <a href="preEditarMarca/<?= $marca->id_marca?>" type="button">Editar</a>
            <p><a href="nombre/<?= $marca->id_marca ?>">Ver botines de <?= $marca->nombre ?> en <?= $marca->sede?></a></p>
            <img src="<?php $marca->foto ?>">
            
        </li>
    <?php } ?>
</ul>

        
    
<?php require_once "templates/footer.phtml"; ?>