<?php 
 require_once "templates/header.phtml";
 require_once "templates/insertar_botines.phtml"; // ver este
 ?>      

<ul>
    <?php foreach($botines as $botin) {?>
        <li>
        <?=$botin->modelo ?>
        <?php } ?>
        <?php foreach($marcas as $marca) {?>
        | Marca: <?= $marca->nombre?>
            <a href="eliminar/<?= $botin->id_botin?>" type="button">Borrar</a>  <!-- ver si va id o botinId (revisar este tipo de cosas)-->
        </li>
    <?php } ?>
</ul>

        <p><small>Mostrando <?=$count?> botines</small></p>
    
<?php require_once "templates/footer.phtml"; ?>