<?php 
 require_once "templates/header.phtml";
 require_once "templates/insertar_botines.phtml"; // ver este
 require_once "app/models/BotinModel.php";
 ?>      

<ul>
    <?php foreach($botinesConMarcas as $botin) {?>
        <li>
            <a href="botin/<?= $botin->id_botin?>"> <?= $botin->modelo ?> | Marca: <?=($botin->nombre_marca)?> </a>
            <a href="eliminar/<?= $botin->id_botin?>" type="button">Borrar</a>  <!-- ver si va id o botinId (revisar este tipo de cosas)-->
        </li>   
    <?php  }?>
</ul>

        <p><small>Mostrando <?=$count?> botines</small></p>
    
<?php require_once "templates/footer.phtml"; ?>